config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'welcome#index'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users # add restful user resource

end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase } # downcase everything before saving to ensure uniqueness
    validates(:name, presence: true,  length: { maximum: 50 })
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password  # implements hashed password
    validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create # find user when POST form is submitted
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user     # this function is defined in session helper
      redirect_to user

    else
      # Create an error message.
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
    before_action :correct_user,   only: [:edit, :update]

    def index
    end
    
    
    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            # successful save
        else
            render 'edit'
        end
    end
    
    
    def edit
        @user = User.find(params[:id])
    end
    
    def new
       @user = User.new 
    end
    
    def show
        @user = User.find(params[:id])
    end    
    
    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            flash[:success] = "Welcome to xnxm.co"
            redirect_to @user # Handle a successful save.
        else
            flash[:danger] = 'Invalid login details'
            render 'new'
        end
    end
    
    # all following methods are private

      private
    
        def user_params
          params.require(:user).permit(:name, :email, :password,
                                       :password_confirmation)
        end
        
        # is user logged in?
        def logged_in_user
            unless logged_in?
                flash[:danger] = "Please log in."
                redirect_to login_url
            end
        end
        
        # is it the correct user
        def correct_user
            @user = User.find(params[:id])
            redirect_to(root_url) unless @user == current_user
        end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
      session[:user_id] = user.id
    end
  
    # get current logged in user
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    # is there a user logged in?
    def logged_in?
        !current_user.nil?
    end
    
    # log out current user
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= debug(params) if Rails.env.development? %>
  <% flash.each do |message_type, message| %>
    <%= message_type %>
    <%= message %>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/users/edit.html.erb
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes" %>
    <% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
      There are <%= pluralize(@user.errors.count, "error") %>.
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

app/views/users/index.html.erb
<h1> Hello </h1>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Password Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Signup"%>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<%= @user.email %>

    <%= link_to "Log out", logout_path, method: "delete" %>
    <%= link_to "Settings", edit_user_path(current_user) %>
    

app/views/welcome/index.html.erb
<h1>xnxm.co</h1>